import {
  index,
  layout,
  type RouteConfig,
  route,
} from "@react-router/dev/routes";

export default [
  route("health", "routes/health.ts"),
  route("api/commission/prepare", "routes/api/commission-prepare.ts"),
  route("api/commission/submit", "routes/api/commission-submit.ts"),
  route("language/:locale", "routes/language-preference.ts"),
  // Content Studio (docs/admin-architecture.md §2.1). The owner guard is the
  // root's middleware, so it covers the shell and the preview branch alike.
  route("studio", "routes/studio/root.tsx", [
    layout("routes/studio/shell.tsx", [
      index("routes/studio/home.tsx"),
      route("projects", "routes/studio/projects/list.tsx"),
      route("projects/new", "routes/studio/projects/new.tsx"),
      route("projects/:id", "routes/studio/projects/edit.tsx"),
      route("music", "routes/studio/music/list.tsx"),
      route("music/new", "routes/studio/music/new.tsx"),
      route("music/:id", "routes/studio/music/edit.tsx"),
      route("recognition", "routes/studio/recognition/list.tsx"),
      route("recognition/new", "routes/studio/recognition/new.tsx"),
      route("recognition/:id", "routes/studio/recognition/edit.tsx"),
      route("writing", "routes/studio/writing/list.tsx"),
      route("writing/new", "routes/studio/writing/new.tsx"),
      route("writing/:id", "routes/studio/writing/edit.tsx"),
      route("services", "routes/studio/services/list.tsx"),
      route("services/new", "routes/studio/services/new.tsx"),
      route("services/pricing", "routes/studio/services/pricing.tsx"),
      route("services/terms", "routes/studio/services/terms.tsx"),
      route("services/:id", "routes/studio/services/edit.tsx"),
      route("social", "routes/studio/social.tsx"),
      route("media", "routes/studio/media/library.tsx"),
      route("media/:id", "routes/studio/media/detail.tsx"),
      route("homepage", "routes/studio/homepage.tsx"),
      route("settings", "routes/studio/settings/index.tsx"),
      route("settings/brand", "routes/studio/settings/brand.tsx"),
      route("settings/site", "routes/studio/settings/site.tsx"),
      route("settings/taxonomies", "routes/studio/settings/taxonomies.tsx"),
      route("settings/footer", "routes/studio/settings/footer.tsx"),
      route("commissions", "routes/studio/commissions/list.tsx"),
      route("commissions/status", "routes/studio/commissions/status.ts"),
      route(
        "commissions/student-discount",
        "routes/studio/commissions/student-discount.ts",
      ),
      route("commissions/cleanup", "routes/studio/commissions/cleanup.ts"),
    ]),
    route("preview", "routes/studio/preview/layout.tsx", [
      route("home", "routes/studio/preview/home.tsx"),
      route("projects/:id", "routes/studio/preview/project.tsx"),
      route("music/:id", "routes/studio/preview/music.tsx"),
      route("recognition/:id", "routes/studio/preview/recognition.tsx"),
      route("writing/:id", "routes/studio/preview/writing.tsx"),
      route("services/:id", "routes/studio/preview/service.tsx"),
    ]),
  ]),
  route("api/studio/session", "routes/api/studio/session.ts"),
  route("api/studio/slug-check", "routes/api/studio/slug-check.ts"),
  route("api/studio/media-search", "routes/api/studio/media-search.ts"),
  route("api/studio/media-register", "routes/api/studio/media-register.ts"),
  route("api/studio/media", "routes/api/studio/media.ts"),
  route("api/studio/media/:id/content", "routes/api/studio/media-content.ts"),
  // `routes/admin-legacy-redirect.ts` replaces the block below once the
  // integration package has ported every legacy panel (§2.3).
  route("admin", "routes/admin/layout.tsx", [
    index("routes/admin/index.tsx"),
    route("content", "routes/admin/content-index.tsx"),
    route("content/:versionId/edit", "routes/admin/content-edit.tsx"),
    route("content/:versionId/preview", "routes/admin/content-preview.tsx"),
    route("services", "routes/admin/services.tsx"),
    route("terms", "routes/admin/terms.tsx"),
    route("works", "routes/admin/works.tsx"),
    route("links", "routes/admin/links.tsx"),
    route("posts", "routes/admin/posts.tsx"),
    route("posts/:versionId/edit", "routes/admin/post-edit.tsx"),
    route("cases", "routes/admin/cases.tsx"),
    route("cases/status", "routes/admin/case-status.ts"),
    route("cases/student-discount", "routes/admin/student-discount.ts"),
    route("cases/cleanup", "routes/admin/cleanup-confirm.ts"),
  ]),
  index("routes/language-redirect.tsx"),
  route(":lang", "routes/public/layout.tsx", [
    index("routes/public/home.tsx"),
    route("commission", "routes/public/commission-index.tsx"),
    route("commission/success", "routes/public/commission-success.tsx"),
    route("commission/:category", "routes/public/commission-category.tsx"),
    route(
      "commission/:category/:service",
      "routes/public/commission-service.tsx",
    ),
    route("mixing", "routes/public/mixing-index.tsx"),
    route("mixing/full", "routes/public/mixing-full.tsx"),
    route("mixing/vocal", "routes/public/mixing-vocal.tsx"),
    route("song-transition", "routes/public/transition-index.tsx"),
    route("song-transition/simple", "routes/public/transition-simple.tsx"),
    route("song-transition/edit", "routes/public/transition-edit.tsx"),
    route("works", "routes/public/works-index.tsx"),
    route("works/:slug", "routes/public/work-detail.tsx"),
    route("services", "routes/public/services-index.tsx"),
    route("services/software", "routes/public/services-software.tsx"),
    route("about", "routes/public/about.tsx"),
    route("writing", "routes/public/writing-index.tsx"),
    route("writing/:slug", "routes/public/writing-detail.tsx"),
    route("other", "routes/public/other-redirect.ts", { id: "other-redirect" }),
    route("other/:slug", "routes/public/other-redirect.ts", {
      id: "other-slug-redirect",
    }),
    route("terms", "routes/public/terms.tsx"),
    route("privacy", "routes/public/privacy.tsx"),
  ]),
] satisfies RouteConfig;
